const modal_active = "modal_active";
const hide = "hide";
const RED = "#f53b49";
const GRAY = "rgba(144,156,181,.3)";

@@include("modal.js")
@@include("city.js")
@@include("phone.js")
@@include("callRequest.js")
@@include("catalogModal.js")
@@include("search.js")
@@include("tabs.js")
@@include("menu.js")
@@include("sign.js")
@@include("slider-banner.js")
@@include("home.js")
@@include("clubs.js")
@@include("brands.js")
@@include("news.js")
@@include("catalogRender.js")
@@include("catalogHome.js")
@@include("catalogClubs.js")
@@include("renderCartItems.js")
@@include("renderCartFooter.js")
@@include("addToCart.js")
@@include("addToTabs.js")
@@include("renderTabsItems.js")
@@include("discount.js")
@@include("sliderCommon.js")
@@include("slider-discount.js")
@@include("slider-news.js")
@@include("fillCart.js")
@@include("fillTabs.js")
